version: '2.3'
services:
  app:
    container_name: app
    image: omegacode/jwt-secured-api-web-server:1.3
    ports:
      - 80:80
    volumes:
      - ./composer.json:/var/www/html/composer.json:cached
      - ./.env:/var/www/html/.env:cached
      - ./src:/var/www/html/src:cached
      - ./res:/var/www/html/res:cached
      - ./public:/var/www/html/public:cached
      - ./keys:/var/www/html/keys:cached
      - ./config:/var/www/html/config:cached
    depends_on:
      - db
  db:
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8
    ports:
      - 3306:3306
    volumes:
      - .database:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=application
  adminer:
    image: adminer:latest
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
