routes:
  -
    name: graphql.index
    route: /graphql
    methods: [get, post]
    action: OmegaCode\JwtSecuredApiGraphQL\Action\GraphQL\IndexAction
    middlewares:
      - OmegaCode\JwtSecuredApiGraphQL\Middleware\SchemaResolverInjectionMiddleware
