services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
  OmegaCode\JwtSecuredApiGraphQL\:
    resource: '../src/*'
    exclude: '../src/{GraphQL},Kernel.php'

  OmegaCode\JwtSecuredApiGraphQL\Action\GraphQL\IndexAction:
    arguments:
      $container: '@service_container'

  OmegaCode\JwtSecuredApiGraphQL\GraphQL\ResolverRegistry:

  OmegaCode\JwtSecuredApiGraphQL\Command\ClearCacheCommand:
    decorates: 'OmegaCode\JwtSecuredApiCore\Command\ClearCacheCommand'
